# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/Librelancer/Librelancer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/Librelancer/Librelancer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/Librelancer/Librelancer/CMakeFiles /home/runner/work/Librelancer/Librelancer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/Librelancer/Librelancer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blurgtext

# Build rule for target.
blurgtext: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blurgtext
.PHONY : blurgtext

# fast build rule for target.
blurgtext/fast:
	$(MAKE) $(MAKESILENT) -f blurgtext/CMakeFiles/blurgtext.dir/build.make blurgtext/CMakeFiles/blurgtext.dir/build
.PHONY : blurgtext/fast

#=============================================================================
# Target rules for targets named unibreak

# Build rule for target.
unibreak: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unibreak
.PHONY : unibreak

# fast build rule for target.
unibreak/fast:
	$(MAKE) $(MAKESILENT) -f blurgtext/CMakeFiles/unibreak.dir/build.make blurgtext/CMakeFiles/unibreak.dir/build
.PHONY : unibreak/fast

#=============================================================================
# Target rules for targets named raqm

# Build rule for target.
raqm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raqm
.PHONY : raqm

# fast build rule for target.
raqm/fast:
	$(MAKE) $(MAKESILENT) -f blurgtext/CMakeFiles/raqm.dir/build.make blurgtext/CMakeFiles/raqm.dir/build
.PHONY : raqm/fast

#=============================================================================
# Target rules for targets named sheenbidi

# Build rule for target.
sheenbidi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sheenbidi
.PHONY : sheenbidi

# fast build rule for target.
sheenbidi/fast:
	$(MAKE) $(MAKESILENT) -f blurgtext/CMakeFiles/sheenbidi.dir/build.make blurgtext/CMakeFiles/sheenbidi.dir/build
.PHONY : sheenbidi/fast

#=============================================================================
# Target rules for targets named plutosvg

# Build rule for target.
plutosvg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 plutosvg
.PHONY : plutosvg

# fast build rule for target.
plutosvg/fast:
	$(MAKE) $(MAKESILENT) -f blurgtext/deps/plutosvg/CMakeFiles/plutosvg.dir/build.make blurgtext/deps/plutosvg/CMakeFiles/plutosvg.dir/build
.PHONY : plutosvg/fast

#=============================================================================
# Target rules for targets named plutovg

# Build rule for target.
plutovg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 plutovg
.PHONY : plutovg

# fast build rule for target.
plutovg/fast:
	$(MAKE) $(MAKESILENT) -f blurgtext/deps/plutosvg/plutovg/CMakeFiles/plutovg.dir/build.make blurgtext/deps/plutosvg/plutovg/CMakeFiles/plutovg.dir/build
.PHONY : plutovg/fast

#=============================================================================
# Target rules for targets named cimgui

# Build rule for target.
cimgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cimgui
.PHONY : cimgui

# fast build rule for target.
cimgui/fast:
	$(MAKE) $(MAKESILENT) -f cimgui/CMakeFiles/cimgui.dir/build.make cimgui/CMakeFiles/cimgui.dir/build
.PHONY : cimgui/fast

#=============================================================================
# Target rules for targets named lancerdecode

# Build rule for target.
lancerdecode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lancerdecode
.PHONY : lancerdecode

# fast build rule for target.
lancerdecode/fast:
	$(MAKE) $(MAKESILENT) -f lancerdecode/CMakeFiles/lancerdecode.dir/build.make lancerdecode/CMakeFiles/lancerdecode.dir/build
.PHONY : lancerdecode/fast

#=============================================================================
# Target rules for targets named crnlibglue

# Build rule for target.
crnlibglue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crnlibglue
.PHONY : crnlibglue

# fast build rule for target.
crnlibglue/fast:
	$(MAKE) $(MAKESILENT) -f crnlibglue/CMakeFiles/crnlibglue.dir/build.make crnlibglue/CMakeFiles/crnlibglue.dir/build
.PHONY : crnlibglue/fast

#=============================================================================
# Target rules for targets named thorncompiler

# Build rule for target.
thorncompiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 thorncompiler
.PHONY : thorncompiler

# fast build rule for target.
thorncompiler/fast:
	$(MAKE) $(MAKESILENT) -f thorncompiler/CMakeFiles/thorncompiler.dir/build.make thorncompiler/CMakeFiles/thorncompiler.dir/build
.PHONY : thorncompiler/fast

#=============================================================================
# Target rules for targets named lancerdialogs

# Build rule for target.
lancerdialogs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lancerdialogs
.PHONY : lancerdialogs

# fast build rule for target.
lancerdialogs/fast:
	$(MAKE) $(MAKESILENT) -f lancerdialogs/CMakeFiles/lancerdialogs.dir/build.make lancerdialogs/CMakeFiles/lancerdialogs.dir/build
.PHONY : lancerdialogs/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... blurgtext"
	@echo "... cimgui"
	@echo "... crnlibglue"
	@echo "... lancerdecode"
	@echo "... lancerdialogs"
	@echo "... plutosvg"
	@echo "... plutovg"
	@echo "... raqm"
	@echo "... sheenbidi"
	@echo "... thorncompiler"
	@echo "... unibreak"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

